server:
  port: 8080

spring:
  application:
    name: crediya-reporting-service

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    displayRequestDuration: true
    showExtensions: true
    showCommonExtensions: true
  packages-to-scan: com.crediya.api
  paths-to-match: /api/v1/reports
  cache:
    disabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  server:
    port: 8080

logging:
  level:
    com.crediya: INFO
    org.springframework.web: DEBUG
    org.springdoc: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"