server:
  port: 8080
spring:
  application:
    name: "CrediyaReporting"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
aws:
  region: "us-east-2"

app:
  dynamo:
    table: "crediya-reports"
    gsi: "metricId-updatedAt-index"
    pk: "global-report"

security:
  secret: "QnE1T2lXbVRhV3RzR2VOUXlHaFZ2d2dyU2p2a1R2TnM="
  expiration-sec: 3600
  issuer: "autenticacion-service"
  issuer-uri: ""

entrypoint:
  sqs:
    region: "us-east-2"
    queueUrl: "https://sqs.us-east-2.amazonaws.com/889522049804/generate-reports-queue"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
